---
title: "Rapport de laboratoire 3"
subtitle: "MTH8408"
author:
  - name: Yasmine Amami
    email: yasmineamami.adresse@polymtl.ca
    affiliation:
      - name: Polytechnique Montréal
format:
  pdf:
    keep-tex: false
    documentclass: article
    include-in-header:
      - text: |
            \usepackage{eulervm}
            \usepackage{xspace}
            \usepackage[francais]{babel}
    geometry:
      - margin=1in
    papersize: letter
    colorlinks: true
    urlcolor: blue
engine: julia
---

```{julia}
#| output: false
using Pkg
Pkg.activate("labo3_env")
Pkg.add("ADNLPModels")
Pkg.add("NLPModels")
Pkg.add("LDLFactorizations")
Pkg.add("Krylov")
using LinearAlgebra,Printf,ADNLPModels,NLPModels, LDLFactorizations,Krylov
```

# Contexte

Dans ce laboratoire, on demande d'implémenter deux méthodes basées sur la méthode de Newton pour le problème
$$
  \min_x \ f(x)
$$ {#eq-nlp}
où $f : \mathbb{R}^n \to \mathbb{R}$ est deux fois continûment différentiable.

# Question 1

En cours, nous avons vu la méthode de Newton modifiée avec recherche linéaire inexacte pour résoudre ([-@eq-nlp]).

Dans cette question, on demande d'implémenter et de tester cette méthode *en utilisant une factorisation modifiée* de $\nabla^2 f(x_k)$.

Votre implémentation doit avoir les caractéristiques suivantes :

1. prendre un `AbstractNLPModel` en argument ;
1. un critère d'arrêt absolu et relatif sur le gradient de l'objectif ;
2. un critère d'arrêt portant sur le nombre d'itérations (le nombre maximum d'itérations devrait dépendre du nombre de variables $n$ du problème) ;
2. toujours démarrer de l'approximation initiale spécifiée par le modèle ;
3. allouer un minimum en utilisant les opérations vectorisées (`.=`, `.+`, `.+=`, etc.) autant que possible ;
6. votre fonction principale doit être documentée---reportez-vous à [https://docs.julialang.org/en/v1/manual/documentation](https://docs.julialang.org/en/v1/manual/documentation) ;
7. votre fonction doit faire afficher les informations pertinentes à chaque itération sous forme de tableau comme vu en cours.

Tester votre implémentation sur le problème polynomial vu en classe et les problèmes non linéaires de la section *Problèmes test* ci-dessous.

```{julia}
"""
    newton_modifiee(model, eps_a=1.0e-5, eps_r=1.0e-5)

Résout un problème d'optimisation non linéaire sans contraintes en utilisant la méthode de Newton modifiée avec recherche linéaire inexacte.

# Arguments
- `model`: Un modèle d'optimisation non linéaire conforme à l'interface AbstractNLPModel
- `eps_a`: Critère d'arrêt absolu sur la norme du gradient (par défaut: 1.0e-5)
- `eps_r`: Critère d'arrêt relatif sur la norme du gradient (par défaut: 1.0e-5)
"""
function newton_modifiee(model, eps_a=1.0e-5, eps_r=1.0e-5)
  x = model.meta.x0
  n = length(x)
  g0 = grad(model, x)
  seuil = eps_a + eps_r * norm(g0)

  println(" iter  |  f(x)       | |grad| | pas | slope")
  println("-------|-------------|--------|-----|-------")

  for iter in 1:10*n
    f = obj(model, x)
    g = grad(model, x)
    if norm(g) <= seuil
      break 
    end   

    H = Symmetric(triu(hess(model, x)))
    # On utilise la factorisation LDL modifiée
    LDL = ldl_analyze(H)
    LDL.tol = Inf
    LDL.r1 = 1.0e-5
    LDL = ldl_factorize!(H, LDL)
    d = -LDL \ g

    # On utilise Armijo
    t = 1.0 
    slope = dot(d, g)
    while obj(model, x + t*d) > f + 1e-4 * t * slope
      t *= 0.5
    end     
    
    x += t*d

    @printf("%4d  | %8.2e | %10.2e | %6.2e | %6.2e\n", iter, f, norm(g), t, slope)
  end 
  return x
end
```

# Question 2

Dans cette question, on demande d'implémenter la méthode de Newton inexacte pour résoudre ([-@eq-nlp]).

Votre implémentation doit avoir les mêmes caractéristiques qu'à la question 1.

Il faut de plus ajuster votre méthode de manière à encourager la convergence locale superlinéaire.

Tester votre implémentation sur le problème polynomial vu en classe et les problèmes non linéaires de la section *Problèmes test* ci-dessous.

```{julia}
"""
    newton_inexacte(model, eps_a=1.0e-5, eps_r=1.0e-5; verbose=true)

Résout un problème d'optimisation non linéaire sans contraintes en utilisant 
la méthode de Newton inexacte avec un solveur itératif pour les systèmes linéaires.

# Arguments
- `model`: Un modèle d'optimisation non linéaire conforme à l'interface AbstractNLPModel
- `eps_a`: Critère d'arrêt absolu sur la norme du gradient (par défaut: 1.0e-5)
- `eps_r`: Critère d'arrêt relatif sur la norme du gradient (par défaut: 1.0e-5)
"""
function newton_inexacte(model, eps_a=1.0e-5, eps_r=1.0e-5)
  x = model.meta.x0  
  n = length(x)
  g0 = grad(model, x)
  seuil = eps_a + eps_r * norm(g0)

  println(" iter  |  f(x)       | |grad| | pas | slope | η")
  println("-------|-------------|--------|-----|-------|---")

  for iter in 1:10*n
    f = obj(model, x)
    g = grad(model, x)
    if norm(g) <= seuil
      break 
    end
    
    H = hess(model, x)    
    # On définit η pour encourager la convergence superlinéaire
    η = min(0.5, sqrt(norm(g)))
    # On résout le système avec CG
    d, stats = Krylov.cg(H, -g, rtol=η, itmax=n, linesearch=true)
    # On utilise ici Armijo 
    t = 1.0
    slope = dot(d, g)
    while obj(model, x + t*d) > f + 1e-4 * t * slope
      t *= 0.5
    end    
    
    x += t * d

    @printf("%4d  | %8.2e | %10.2e | %6.2e | %6.2e | %6.2e\n", iter, f, norm(g), t, slope, η)
  end 
  return x
end
```

# Résultats numériques

## Problèmes test

Votre premier problème test sera le problème polynomial vu en classe.

```{julia}
f(x) = 2*x[1]^3 - 3*x[1]^2 - 6*x[1]*x[2]* (x[1] - x[2] - 1)
model = ADNLPModel(f, [1.5, 0.5])
result1 = newton_modifiee(model)
result2 = newton_inexacte(model)
```

Utiliser ensuite les problèmes non linéaires du dépôt `OptimizationProblems.jl` qui sont sans contraintes et ont 100 variables.
Vous pouvez y accéder à l'aide de l'extrait de code suivant :
```{julia}
#| output: false
Pkg.add("OptimizationProblems")  # collection + outils pour sélectionner les problèmes
using OptimizationProblems, OptimizationProblems.ADNLPProblems

meta = OptimizationProblems.meta
problem_list = meta[(meta.ncon.==0).&.!meta.has_bounds.&(meta.nvar.==100), :name]
problems = (OptimizationProblems.ADNLPProblems.eval(Meta.parse(problem))() for problem ∈ problem_list)
```

Parmis ces problèmes, choisissez-en 3 et illustrez le comportement de chacune des méthodes.

## Validation de la méthode de Newton modifiée

```{julia}

test3 = OptimizationProblems.ADNLPProblems.brybnd()
x3 = newton_modifiee(test3)
```

## Validation de la méthode de Newton tronquée

```{julia}
test1 = OptimizationProblems.ADNLPProblems.srosenbr()
x1 = newton_inexacte(test1)
test2 = OptimizationProblems.ADNLPProblems.argtrig()
x2 = newton_inexacte(test2)
test3 = OptimizationProblems.ADNLPProblems.brybnd()
x3 = newton_inexacte(test3)
```

## Commentaires sur les résultats

- Au niveau de la vitesse de convergence, on constate que la méthode de Newton modifiée semble converger en moins d'itérations sur les problèmes de petite taille, comme le problème polynomial. Toutefois, il faut noter que la méthode modifiée requiert plus de ressources mémoire pour la factorisation complète du Hessien.

- La méthode de Newton inexacte peut parfois nécessiter plus d'itérations internes du solveur CG pour des problèmes mal conditionnés, mais l'adaptation de η permet d'améliorer la convergence.

- Les deux méthodes montrent une réduction rapide de la norme du gradient près de la solution optimale.

